export default [
  {
    id: "animals",
    name: "Animals",
    icon: "animals.svg",
    textColor: "#d49350",
    hoverTextColor: "#a2611e",
    hoverBgColor: "#f6dcc1",
    selectedBgColor: "#e8a764",
  },
  {
    id: "culture",
    name: "Culture",
    icon: "culture.svg",
    textColor: "#7a6db5",
    hoverTextColor: "#7063ab",
    hoverBgColor: "#d6d1ed",
    selectedBgColor: "#988bd3",
  },
  {
    id: "education",
    name: "Education",
    icon: "education.svg",
    textColor: "#7593b6",
    hoverTextColor: "#577598",
    hoverBgColor: "#d8e4f2",
    selectedBgColor: "#9dbbde",
  },
  {
    id: "environment",
    name: "Environment",
    icon: "environment.svg",
    textColor: "#86a537",
    hoverTextColor: "#5e7d10",
    hoverBgColor: "#dbe7bb",
    selectedBgColor: "#a4c355",
  },
  {
    id: "health",
    name: "Health",
    icon: "health.svg",
    textColor: "#bc749d",
    hoverTextColor: "#9e567f",
    hoverBgColor: "#f0d3e4",
    selectedBgColor: "#da92bb",
  },
  {
    id: "humans",
    name: "Humans",
    icon: "humans.svg",
    textColor: "#cca151",
    hoverTextColor: "#906515",
    hoverBgColor: "#f7e5c5",
    selectedBgColor: "#eabf6f",
  },
  {
    id: "justice",
    name: "Justice",
    icon: "justice.svg",
    textColor: "#57989c",
    hoverTextColor: "#397a7e",
    hoverBgColor: "#c8e2e3",
    selectedBgColor: "#75b6ba",
  },
  {
    id: "religion",
    name: "Religion",
    icon: "religion.svg",
    textColor: "#d26544",
    hoverTextColor: "#be5130",
    hoverBgColor: "#f9cdc0",
    selectedBgColor: "#f08362",
  },
  {
    id: "research",
    name: "Research",
    icon: "research.svg",
    textColor: "#59a593",
    hoverTextColor: "#2f806d",
    hoverBgColor: "#bbe9cf",
    selectedBgColor: "#8ac8b9",
  },
];
